### ISSUE TITLE
How to response the register method in a correct way?

### ISSUE THREAD

**Issue by ghost** [ghettovoice/gosip#13]
Hi, ghettovoice. How can I use gosip to add a tag in the response ?  It's said in the RFC3261 

the request has no "to tag" in the to header.

       REGISTER sip:registrar.biloxi.com SIP/2.0
       Via: SIP/2.0/UDP bobspc.biloxi.com:5060;branch=z9hG4bKnashds7
       Max-Forwards: 70
       To: Bob <sip:bob@biloxi.com>
       From: Bob <sip:bob@biloxi.com>;tag=456248
       Call-ID: 843817637684230@998sdasdh09
       CSeq: 1826 REGISTER
       Contact: <sip:bob@192.0.2.4>
       Expires: 7200
       Content-Length: 0

but the response has:
        SIP/2.0 200 OK
        Via: SIP/2.0/UDP bobspc.biloxi.com:5060;branch=z9hG4bKnashds7
         ;received=192.0.2.4
        To: Bob <sip:bob@biloxi.com>;tag=2493k59kd
        From: Bob <sip:bob@biloxi.com>;tag=456248
        Call-ID: 843817637684230@998sdasdh09
        CSeq: 1826 REGISTER
        Contact: <sip:bob@192.0.2.4>
        Expires: 7200
        Content-Length: 0

How can I add a to tag in the response using gosip?

**Comment by ghettovoice** [comment]
Hi @charliecui ,
you can use this helper function https://github.com/ghettovoice/gosip/blob/master/sip/response.go#L190
to build basic response to any sip request (according to RFC). 
Then use with `sip.Response` methods/fields to append/remove/change headers.

```go
response := sip. NewResponseFromRequest("", request, 200, "OK", "")
to, _ := response.To()
to.Params.Add("tag", sip.NewString(localTag))
```
