### ISSUE TITLE
Cannot receive data in udp transport.

### ISSUE THREAD

**Issue by cloudwebrtc** [ghettovoice/gosip#18]
This commit caused the problem.
https://github.com/ghettovoice/gosip/commit/363788fffb829ec6ebad7400481eb6c8805fe7a9#diff-e86e601ae5292817399a481c2c0ed49aeb67b393ac0cddc00d4aa31c491b40b1R105

This modification uses DialUDP to create an independent udp conn to send data.
[udp.go](https://github.com/ghettovoice/gosip/blob/master/transport/udp.go#L105)
```go
	baseConn, err := net.DialUDP(p.network, laddr, raddr)
	...
	key := ConnectionKey(fmt.Sprintf("%s:%s", p.network, baseConn.LocalAddr()))
	conn := NewConnection(baseConn, key, p.network, p.Log())

	logger := log.AddFieldsFrom(p.Log(), conn, msg)
	logger.Tracef("writing SIP message to %s %s", p.Network(), raddr)

	_, err = conn.Write([]byte(msg.String()))
	...
```

but the newly created connection is not added to the p.connections pool,
some code missing here causes no data to be received.
like this.
```go
	err = p.connections.Put(conn, sockTTL)
	if err != nil {
		err = &ProtocolError{
			Err:      err,
			Op:       fmt.Sprintf("put %s connection to the pool", conn.Key()),
			ProtoPtr: fmt.Sprintf("%p", p),
		}
	}
```

@ghettovoice I am a little confused here. Before this modification, we can use the listened udp transport (0.0.0.0:5060) to send data, but after changing to DialUDP, it will cause a new udpConn to be dialed every time UDP data is sent. , Should this be a bug?

**Comment by ghettovoice** [comment]
Hello @cloudwebrtc ,

My idea was to send from the random port via UDP and remove auto appending of `rport` to requests, so the remote sip client should send response over UDP to the port from the topmost Via or default port for this transport.

But as I see from drachtio server log it appends `rport ` to any request even on requests without this param. Very interesting, according to RFC 3581 `rport` should be used only if it was appended by the client. Maybe I'm misunderstand this...

Ok. I'll rollback udp protocol

**Comment by ghettovoice** [comment]
I have made setup of your lib based on the fixed gosip version with drachtio. 
All things going well now except one: 

- here https://github.com/cloudwebrtc/go-sip-ua/blob/11a877103743db3ae153af353c97b42f356c76e1/pkg/ua/ua.go#L91
you pass request recipient to the Via builder. Inside it you overwrite host/port (that are resolved from the network lookup and listened ports) by the values from passed in target. But in this case target is points to the remote addr, so host/port added to the via can be incorrect if you for example listen on non default port.

Here is example:
1. listen UDP on 5080 port
2. send request to `sip:alice@example.com:5060`
3. With current Via builder you finally get something like this
```
INVITE sip:alice@example.com:5060 SIP/2.0
Via: SIP/2.0/UDP 192.168.*.*:5060;branch=...
...
```
Port 5060 from the recipient uri overwrites the port that is actually listening

**Comment by cloudwebrtc** [comment]
Thanks, you are correct, I have fixed it.

**Comment by cloudwebrtc** [comment]
So this issue can be closed now.
