### ISSUE TITLE
How to use this library? What is the main function?

### ISSUE THREAD

**Issue by jinsuojinsuo** [ghettovoice/gosip#24]
How to use this library? What is the main function?

**Comment by ghettovoice** [comment]
It is a pure implementation of RFC3261, but without any backbone for user agent. Only sip transport and transaction layer are here. So to actually use it for something useful you usually need to implement own user agent  and dialog logic for a target application. Simple example is here #3 . 
There is also a basic user agent implementation based on this SIP lib https://github.com/cloudwebrtc/go-sip-ua
