### ISSUE TITLE
nil pointer reference

### ISSUE THREAD

**Issue by thomas-mangin** [ghettovoice/gosip#25]
Hello,

In client_tx.go, the following code can try to call res.Short() when res is nil following a DNS failure to resolve the Host.
```
	err = &TxTransportError{
		fmt.Errorf("transaction failed to send %s: %w", res.Short(), err),
		tx.Key(),
		fmt.Sprintf("%p", tx),
	}
```

This workaround fixes the issue but may not be the right way to handle the problem
```
	reason := "<unknown>"
	if res != nil {
		reason = res.Short()
	}

	err = &TxTransportError{
		fmt.Errorf("transaction failed to send %s: %w", res.Short(), err),
		tx.Key(),
		fmt.Sprintf("%p", tx),
	}
```

**Comment by ghettovoice** [comment]
Hello @thomas-mangin , 
good catch! Can you make a pull request?
