### ISSUE TITLE
question about the requestWithContext function

### ISSUE THREAD

**Issue by yangjiechina** [ghettovoice/gosip#28]
Hi，@ghettovoice trouble you agin
my example code :
```
cancelCtx,cancel := context.WithTimeout(*mainCtx, 5*time.Second)
srv.RequestWithContext(*ctx, *inviteRequest, gosip.WithResponseHandler(func(res sip.Response, request sip.Request) {

    }
}))
```
after 5 seconds，RequestWithContext function does not end.

I know from the server.go source file that requestWithContext will create two coroutines.

The first goroutine when the context is cancelled, the coroutine terminates and the message transaction is cancelled.

The second goroutine when the request message gets a response or the request transaction occur exception, such as a transaction timeout.

The way I understand it, when the context is cancelled, the transaction is cancelled, requestWithContext should be done, so why wait for the response, wait for the transaction to time out. My solution:
```
func (srv *server) requestWithContext(
	ctx context.Context,
	request sip.Request,
	attempt int,
	options ...RequestWithContextOption,
) (sip.Response, error) {
	tx, err := srv.Request(request)
	if err != nil {
		return nil, err
	}
        //...
	go func() {
		defer wg.Done()

		select {
		case <-done:
		case <-ctx.Done():
			if err := tx.Cancel(); err != nil {
				srv.Log().Error("cancel transaction failed", log.Fields{
					"transaction_key": tx.Key(),
				})
			}
		}
	}()
	go func() {
		defer func() {
			close(done)
			wg.Done()
		}()

		for {
			select {
                        //solution code 
			case <-ctx.Done():
				errs <- fmt.Errorf("ctx cancel")
				return
			case err, ok := <-txErrs:
				if !ok {
					txErrs = nil
					// errors chan was closed
					// we continue to pull responses until close
					continue
				}
				errs <- err
				return
			case response, ok := <-txResponses:
				//....
			}
		}
	}()

	var res sip.Response
	select {
	case err = <-errs:
	case res = <-responses:
	}

	wg.Wait()

	return res, err
}

```

**Comment by ghettovoice** [comment]
Hi @yangjiechina ,

> The way I understand it, when the context is cancelled, the transaction is cancelled, requestWithContext should be done, so why wait for the response, wait for the transaction to time out.

requestWithContext waits for the final response. In the case when CANCEL request was handled by the server, then on the main INVITE transaction we should get `487 Request Terminated` response, or something else if INVITE was already finished on the remote server. 
If you see that `requestWithContext` finishes only on transaction time out, then I guess you don't get any final response from the server. Is it right?

**Comment by yangjiechina** [comment]
thanks for you reply.Yes, I use RequestWithContext to send an invite message.Cancel Invite request if there is no resposne whitin 5 seconds.I don't to want wait 32 seconds for the transaction to terminated.it's too long.

**Comment by ghettovoice** [comment]
Do you see some final response from the remote which you are trying to invite?

**Comment by yangjiechina** [comment]
There's no 100 trying provisional response. I'll just do it the way I started. In the second goroutine `case < -ctx.done ` solves my problem. I used PJSIP to have a similar method to cancel the INVITE request before the transaction ends.

**Comment by yangjiechina** [comment]
Thank you for your answer in these two days. I will close this issue
