### ISSUE TITLE
is there any demo for SIP client? thank you 

### ISSUE THREAD

**Issue by williamyang7577** [ghettovoice/gosip#3]

**Comment by ghettovoice** [comment]
Hello @williamyang7577 ,
for now  unfortunately there is no any complete demo. Also the public API is not stable yet.
At the moment I can only provide you with simplest example:

```go
package main

import (
	"log"
	"os"
	"os/signal"
	"syscall"

	"github.com/ghettovoice/gosip"
	siplog "github.com/ghettovoice/gosip/log"
	"github.com/ghettovoice/gosip/sip"
)

func init() {
	siplog.SetLevel(siplog.DebugLevel)
}

func main() {
	stop := make(chan os.Signal, 1)
	signal.Notify(stop, syscall.SIGTERM, syscall.SIGINT)

	srv := gosip.NewServer(&gosip.ServerConfig{})
	
	srv.OnRequest(sip.INVITE, func (request sip.Request, tx sip.ServerTransaction) {
		log.Println("RECEIVE REQUEST")
		log.Println(request)


		srv.RespondOnRequest(request, 200, "OK", "", []sip.Header{
			&sip.ContactHeader{
				DisplayName: sip.String{"Bob"},
				Address: &sip.SipUri{
					FUser: sip.String{"+123456789"},
					FHost: "example.com",
				},
			},
		})
	})

	if err := srv.Listen("udp", "0.0.0.0:5060"); err != nil {
		panic(err)
	}

	<-stop

	srv.Shutdown()
}
```

**Comment by williamyang7577** [comment]
Hi ghettovoice,
Thank you. Is this Demo for Server? Could you please give me some hints about SIP client?

William

**Comment by ghettovoice** [comment]
This struct `srv ` is sip server and sip client into one. I know the name is not the best :)

It works as a server when you register various handlers for sip requests through `srv.OnRequest` call. In each request handler you doing something, for exmaple like Dialog initialization, and send a response. Dialog and User agent is not in this lib yet, you should implement them by yourself.

To make a request as a client there is [`srv.Request`](https://github.com/ghettovoice/gosip/blob/master/server.go#L181) method, that returns to you `sip.ClientTransaction`. Or you can use [`srv.RequestWithContext`](https://github.com/ghettovoice/gosip/blob/master/server.go#L189) that is a wrapper around previous method and handles handles multiple responses from client transaction.

Also there is a method to send sip message directly through the transport layer, avoiding transaction layer: [`srv.Send`](https://github.com/ghettovoice/gosip/blob/master/server.go#L362)

In the `github.com/ghettovoice/gosip/sip` you can find various helpers and widely used sip headers. If something is missed you alway can register custom header by yourself by implementing sip.Header interface.

**Comment by williamyang7577** [comment]
Hi ghettovoice,
Thank you very much, I will try it.

B.R
William

**Comment by negbie** [comment]
Just for your info https://github.com/cloudwebrtc/go-sip-ua this is a thin wrapper around gosip
