### ISSUE TITLE
Go routine leaks with tcp connection?

### ISSUE THREAD

**Issue by JamesYin689** [ghettovoice/gosip#30]
![288b03e9bf18baf675a18b0890742ca](https://user-images.githubusercontent.com/20217323/134289150-5c52a70d-fa7d-4a48-8cac-03cbac1a9b48.png)
![1632289347(1)](https://user-images.githubusercontent.com/20217323/134289272-610973a6-4f10-4bdd-9c6e-324fff5107cf.png)

When a tcp connection received, this go routine will add once, but when the connection disconnect,the go routine still exist.

**Comment by ghettovoice** [comment]
Hello @JamesYin689,
thanks for report! 
I will review this handler ASAP.

**Comment by ghettovoice** [comment]
Fixed
