### ISSUE TITLE
Response cannot be sent due to the incorrect transport

### ISSUE THREAD

**Issue by JamesYin689** [ghettovoice/gosip#31]
Hi @ghettovoice,
A client send out a request using UDP, and the length of the message is greater than MTU(1500 bytes).
I'am using `NewResponseFromRequest` to create a response from the request. But  `req.Transport()` returns "TCP", which caused the response cannot be sent back to the client.
The `Transport` function changes origional "UDP" to "TCP" in request.go
[https://github.com/ghettovoice/gosip/blob/master/sip/request.go](url)
`
	if tp == "UDP" && len(req.String()) > int(MTU)-200 {
		tp = "TCP"
	}
`
I deleted the above code, and the issued was fixed. So I think the code may be deleted, do you agree with me or any other better way to avoid the issue?

**Comment by ghettovoice** [comment]
Hi @JamesYin689 ,
thanks for report!

Seems that I need to mark somehow inbound requests and always use the transport by which they are arrived.
This overwrite based on most common MTU value here to avoid incomplete sip requests on the other side.
