### ISSUE TITLE
[BUG] panic error

### ISSUE THREAD

**Issue by chenparty** [ghettovoice/gosip#39]
It looks like I'd been attacked, and then the program occurred panic err
![image](https://user-images.githubusercontent.com/16755257/164168242-577d8cdb-2ea9-4ae1-96f8-6efe9de7259c.png)

Anything can help me plz?

**Comment by ghettovoice** [comment]
Hello @chenparty!

sorry, I missed the nil checking in the main request handler 🤦 
I will fix it ASAP.
Thanks for report!

**Comment by ghettovoice** [comment]
@chenparty upgrade pls

**Comment by chenparty** [comment]
Thanks, I'll upgrade it now.
