### ISSUE TITLE
PBX server

### ISSUE THREAD

**Issue by oldEvenHatoen** [ghettovoice/gosip#4]
Is it possible to build a PBX server, based on this project?

**Comment by ghettovoice** [comment]
Hello @oldEvenHatoen,
PBX usually should support a lot of features, protocols and etc, that this project doesn't include.
This project implements only RFC3261 in part of transport and transaction layers.
So to implement PBX server you need to develop UA logic, dialog/session handling, add SDP/RTP support and so on. There is a lot of work I think

**Comment by cloudwebrtc** [comment]
@ghettovoice I am trying to write a sip ua based on your library to support client, b2bua, and webrtc2sip gateway

https://github.com/cloudwebrtc/go-sip-ua
