### ISSUE TITLE
sip server blocked while receiving a large UDP message

### ISSUE THREAD

**Issue by JamesYin689** [ghettovoice/gosip#40]
After receiving a UDP message that message length is larger than 4096, the udp server is blocked and cann't recover any more.
parser Write blocked,
![image](https://user-images.githubusercontent.com/20217323/174422679-f4956e21-3a85-4be2-9d99-3da9d1d129d2.png)
parser parse blocked,
![image](https://user-images.githubusercontent.com/20217323/174422751-d5363571-327d-4c8c-9c16-1c37690a76e3.png)
parse buffer,
![image](https://user-images.githubusercontent.com/20217323/174422855-dba16679-4497-45bd-843b-9c35b2ca67b1.png)

The issue can be reproduced. I try to fix the issue, using the following code,the issue can be fixed.
![image](https://user-images.githubusercontent.com/20217323/174422917-9e35f391-7c11-4eba-808b-d07e72c97849.png)

**Comment by YiuTerran** [comment]
On an Ethernet, the maximum amount of data in a frame is ordinarily 1500 bytes. 

If your packet is bigger than this, you should split your data into multi packets.

**Comment by ghettovoice** [comment]
@JamesYin689 
you are right about possible deadlock in the parser. I have fixed it, so it shouldn't hang now even for a big message.

However take a note (as @YiuTerran wrote above)  that transmission of such big messages over UDP probably will work correctly only on localhost interface. For other interfaces TCP should be used

**Comment by JamesYin689** [comment]
@ghettovoice Thanks for replying. Because the sip clients come from different companies，and they are out of our control. I tested the latest version, but the parser paniced while receiving a big udp message, the testcase is attached.
[testcase.txt](https://github.com/ghettovoice/gosip/files/9016169/testcase.txt)

**Comment by ghettovoice** [comment]
@JamesYin689 thanks for report, should work now.

**Comment by JamesYin689** [comment]
Test OK for a short time.
