### ISSUE TITLE
Goroutine leaks with CANCEL

### ISSUE THREAD

**Issue by vicvon** [ghettovoice/gosip#42]
There is a problem with the UAS state machine，while a CANCEL request send by UAC for pending INVITE, the goroutine leaks.
![微信截图_20220801164927](https://user-images.githubusercontent.com/13044301/182110925-709f093a-5c28-4b4f-8641-c16538ce3509.png)

**Comment by ghettovoice** [comment]
Hello @vicvon ,
can you clarify a bit? do you respond with 487 code on server INVITE tx?

Take a note that:
UAS state machine doesn't stop the tx itself, instead when UAS got a CANCEL it passes it up to application via channel returned by `tx.Cancels()`. So the app on CANCEL should answer 200 OK and also send 487 on the cancelling INVITE. Sending final 487 response on server INVITE tx will move it into completed state, where UAS waits ACK from UAC and stop tx or timer_H trigger and stop tx. 
So there is possible leak cause you forget respond with final response on transaction or it waits some time for ACK from UAC.
