### ISSUE TITLE
[Feature Request]: pure client mode

### ISSUE THREAD

**Issue by YiuTerran** [ghettovoice/gosip#43]
In my case, I would like to mock lots of sip devices to communicate with the upstream UA using TCP.

For now, I must listen to a port for a device, but the communication will not use the server part at all. Because the upstream will just use the TCP connection set up by the client. 

So, maybe we need a pure TCP client without having to listen on any port.

**Comment by YiuTerran** [comment]
I currently use `jordwest/mock-conn` to mock a TCP listener for my purpose.

**Comment by ghettovoice** [comment]
Hello @YiuTerran ,
probably I can append tp protocol auto-intialization also in the `Send` message... And I hope it will not break anything.
This change should allow sending SIP requests without listeners setup, but sure will correctly work only with reliable transports

**Comment by ghettovoice** [comment]
@YiuTerran I have pushed a patch to the `dev` branch. Can you try it in your app/env?
You can install it with `go get github.com/ghettovoice/gosip@dev`

**Comment by YiuTerran** [comment]
> @YiuTerran I have pushed a patch to the `dev` branch. Can you try it in your app/env? You can install it with `go get github.com/ghettovoice/gosip@dev`

ok, i will try it next week. thanks very much~

**Comment by YiuTerran** [comment]
Sorry for late reply. I just test the `dev` branch, it looks that everything is fine without listening any port when using TCP.

Thanks for your help~

**Comment by YiuTerran** [comment]
@ghettovoice But i just review the code, found a little problem:

```go
func (tpl *layer) getProtocol(network string) (p Protocol, err error) {
	var ok bool
       // not goroutine safe, we need some func like `LoadOrStore` here
	p, ok = tpl.protocols.get(protocolKey(network))
	if ok {
		return
	}
	p, err = protocolFactory(
		network,
		tpl.pmsgs,
		tpl.perrs,
		tpl.canceled,
		tpl.msgMapper,
		tpl.Log(),
	)
	if err != nil {
		return nil, err
	}
	tpl.protocols.put(protocolKey(p.Network()), p)
	return p, nil
}
```

**Comment by ghettovoice** [comment]
`tpl.protocols` points to internal map+mutex store

**Comment by YiuTerran** [comment]
> `tpl.protocols` points to internal map+mutex store

Yeah, but data race happens between `get` and `put`. It's not a big problem.

**Comment by YiuTerran** [comment]
> Ah, I see now. Do you talking about that get and put should be made as single "atomic" action?

Yeah, maybe it's better😃
