### ISSUE TITLE
how to send 487 when i recieve cancel

### ISSUE THREAD

**Issue by czk630597526** [ghettovoice/gosip#47]
hello:
code like this,when i recievd cancel ,it seems hard to send 487 when i using the transaction
```
cancel := <-tx.Cancels()
		if cancel != nil {
			response := sip.NewResponseFromRequest(req, cancel, 200, "ok", "")
			tx.Respond(response)
}
```

and how to send 487

**Comment by ghettovoice** [comment]
Hello @czk630597526 ,
you can access origin transaction request via `tx.Origin()` call. This is the origin request that you should finish with 487 response.
