### ISSUE TITLE
listen on both udp and tcp

### ISSUE THREAD

**Issue by XunChangqing** [ghettovoice/gosip#50]
According to [18.2.1](https://www.rfc-editor.org/rfc/rfc3261#section-18.2.1) Receiving Requests
> 
For any port and interface that a server listens on for UDP, it MUST listen on that same port and interface for TCP.  This is because a message may need to be sent using TCP, rather than UDP, if it is too large.

Should I listen on the same port for both udp and tcp?

**Comment by ghettovoice** [comment]
Hello @XunChangqing ,

yes, you are right. To be compliant with RFC, you should listen both on the same port, usually 5060.
