### ISSUE TITLE
new goroutines for user handlers

### ISSUE THREAD

**Issue by XunChangqing** [ghettovoice/gosip#52]
In function serve, we add waitgroup, launch a goroutine for each request.
```go
			srv.hwg.Add(1)
			go srv.handleRequest(tx.Origin(), tx)
```
In function handleRequest, the waitgroup is done.
```go
func (srv *server) handleRequest(req sip.Request, tx sip.ServerTransaction) {
	defer srv.hwg.Done()
```
But in the end of handleRequest, we launch another goroutine to run the user handler.
```go
	go handler(req, tx)
}
```
When the sever is shutdown, goroutines running user handlers may leak?

**Comment by ghettovoice** [comment]
Hello @XunChangqing ,
you are right, thanks for report. It's actually a bug, no need to launch handler in additional goroutine.
