### ISSUE TITLE
received_by and received_from for multi port listening

### ISSUE THREAD

**Issue by azhaocn** [ghettovoice/gosip#53]
In cases of listening at 0.0.0.0:5060 or multi interfaces,  for response of sip message, it needs to present the contact header, such as Contact: <sip:192.168.1.100:5060;transport=udp>,  is there a way to retrive the recevied from and received by address from transcation?

**Comment by ghettovoice** [comment]
Hello @azhaocn ,
in case of listening multiple interfaces you need manually setup address in contact header by which your UA is available and ready to work.
Cause, even if you take address from connection that got a message, `conn.LocalAddr()` returns something like `[::]:5060`.

**Comment by azhaocn** [comment]
How about if we setup multi listener implicitly such as: 192.168.1.1:5060  and 192.168.2.1:5060, and is it possible to retrive the correct local ip from conn.LocalAddr()?

**Comment by ghettovoice** [comment]
I got it, sorry for delay. 
You can get address at which inbound message was received via `msg.Destination()` method. And actual remote address via `msg.Source()`. These fields are filled from conn.LocalAddr, conn.RemoteAddr results.

Usually SIP used with static public IP, so you already know it and port at which you are listen for inbound messages. So this IP/domain usually used to fill Contact host part. This is why I didn't get what the problem with filling a contact with correct address.
