### ISSUE TITLE
i got this pannic 

### ISSUE THREAD

**Issue by czk630597526** [ghettovoice/gosip#59]
![image](https://github.com/ghettovoice/gosip/assets/88134686/0fcefaf1-2d30-4322-83c8-1209942d4337)
in connection_pool line 690
It tells me this channel output has been closed
![image](https://github.com/ghettovoice/gosip/assets/88134686/cce7383a-c970-4f7c-b474-b7583a70d72b)
![image](https://github.com/ghettovoice/gosip/assets/88134686/ec56bbc8-802e-48b0-af6a-a96c32eca867)

did we need protect by wg like what i did

**Comment by ghettovoice** [comment]
Hello @czk630597526 ,
thanks for report👍
It should be fixed now in the latest `master` version
