### ISSUE TITLE
Could this be a bug in getOrCreateConnection in tcp.go

### ISSUE THREAD

**Issue by jonathan-leonardi** [ghettovoice/gosip#6]
The below snippet :
if err != nil {
		tcp.Log().Debugf("connection for remote address %s %s not found, create a new one", tcp.Network(), raddr)

		tcpConn, err := net.DialTCP(network, nil, raddr)
		if err != nil {
			return nil, &ProtocolError{
				err,
				fmt.Sprintf("connect to %s %s address", tcp.Network(), raddr),
				fmt.Sprintf("%p", tcp),
			}
		}

		conn = NewConnection(tcpConn, key, tcp.Log())

		err = tcp.connections.Put(conn, sockTTL)
	}

	return conn, err

Could it be the intention is to reuse err variable inside the if block ?
This line will create new err variable inside if block. So if err is nil the if block, it will still return error from the function.

tcpConn, err := net.DialTCP(network, nil, raddr)

**Comment by ghettovoice** [comment]
Hello @jonathan-leonardi ,
I'm agree that there is a bug, error from this line `err = tcp.connections.Put(conn, sockTTL)` never returned.
But I'm not full understand your issue about still returned error. Do you get error from this function even if connection was created?
