### ISSUE TITLE
leak memoy

### ISSUE THREAD

**Issue by Modestying** [ghettovoice/gosip#64]
I use `https://github.com/cloudwebrtc/go-sip-ua.git` repo to finish something and this repo import `gosip`

I run bench test,and meet memeory problem

![WechatIMG85](https://github.com/ghettovoice/gosip/assets/68675769/35a56aff-1e84-4018-a272-50bf0eef3869)

![WechatIMG87](https://github.com/ghettovoice/gosip/assets/68675769/f14adea4-b37a-4dc7-805c-85826e2ebf7e)

I think maybe my program didn't delete `tx`  which created by `NewServerTx`

I read `gosip` source code and location `transaction.commonTx`. I can't find  anyone write data to `commonTx.done `,so I don't understand how did `transaction.layer.serveTransaction()` exit

```go
	for {
		select {
		case <-txl.canceled:
			logger.Info("transaction canceled")
			tx.Terminate()
			return
		case <-tx.Done(): // where write data?
			logger.Info("transaction done")
			return
		}
	}

```

Can you tell me how where write data to `tx.done`?

**Comment by ghettovoice** [comment]
Hello @Modestying ,
do you find answer on your question?

transaction's `done` channel is closed in the delete method:
https://github.com/ghettovoice/gosip/blob/master/transaction/server_tx.go#L461
https://github.com/ghettovoice/gosip/blob/master/transaction/client_tx.go

This method is usually called by tx timer callbacks or by state machine.

**Comment by angwangiot** [comment]
I have the same problem, a large number of goroutines did not exit in transaction.layer.serveTransaction().

**Comment by ghettovoice** [comment]
Hello @angwangiot ,
ok, I will try search possible problems in transaction's FSM.

For a while, do you sure that you  respond with final status on each inbound sip request that goes through transaction layer?
For example, the INVITE transaction FSM works such way that, if you didn't answer with final response, it will stay in proceeding state infinitely.

**Comment by angwangiot** [comment]
Hi @ghettovoice，
I think I found out why, I did not reply to the final status after receiving the registration message.

**Comment by angwangiot** [comment]
Hi @ghettovoice，
I think I found out why, I did not reply to the final status after receiving the registration message.

**Comment by angwangiot** [comment]
Hi @ghettovoice，
I think I found out why, I did not reply to the final status after receiving the registration message.
