### ISSUE TITLE
Add "rport" in via to support NAT

### ISSUE THREAD

**Issue by FireTiger23** [ghettovoice/gosip#66]
Problem:
Can not connenct to SIP server when client behind a NAT network.

Request Log:

REGISTER sip:1000@172.27.0.8:7060 SIP/2.0

Via: SIP/2.0/UDP 192.168.1.187:50066;branch=z9hG4bK.iJM9FQ5m5ZRW0ZJZTAvNGlTyN9JPA6Nl
......
What's expected:

REGISTER sip:1000@172.27.0.8:7060 SIP/2.0

Via: SIP/2.0/UDP 192.168.1.187:50066;rport;branch=z9hG4bK.iJM9FQ5m5ZRW0ZJZTAvNGlTyN9JPA6Nl
......
Solution:
Add an additional "rport" parameter in "Via" when request is prepared. ([RFC3581](https://www.ietf.org/rfc/rfc3581.txt))
I submitted a PR draft at https://github.com/cloudwebrtc/go-sip-ua/pull/98. This PR only checks the functionality, not the configuration, which may need to be added.

**Comment by ghettovoice** [comment]
Hello @FireTiger23 ,
I'm sure, that `rport` parameter should be added in the cloudwebrtc/go-sip-ua via func arg or config option, as you done it your pull request.

There is in the gosip just a basic constructor for sip.Request. After the request is constructed, you can add any additional headers or parameters. Adding by default `rport` to all requests here can break the most basic use case, when UA sends request from rand UDP port, but listens on a fixed 5060 port.
