### ISSUE TITLE
sip server may blocked while Shutdown() , because connectionPool may blocked while cancel

### ISSUE THREAD

**Issue by liangtu1** [ghettovoice/gosip#68]
while connectionPool cancel,  if connectionPool.serveHandlers() return first, connectionHandler and connectionPool will deadlock.

1. connectionPool.serveHandlers() receive msg and cancel ,then return ,  so nobody will read pool.hmess
```go
func (pool *connectionPool) serveHandlers() {
...
	for {
...
		select {
		case msg, ok := <-pool.hmess:
...
			select {
			case <-pool.cancel:
				return
...
		case err, ok := <-pool.herrs:
...
```

2. connectionHandler read next message and handleMessage() block here: handler.output <- msg,  handler.output is pool.hmess
```go
func (handler *connectionHandler) handleMessage(msg sip.Message, raddr string) {
...
	// pass up
	handler.output <- msg
```

3. Finally run pool.dispose() and  block here: pool.hwg.Wait(), wait for all connectionHandler done
```go
func (pool *connectionPool) dispose() {
...
	pool.DropAll()
	pool.hwg.Wait()
...
	// stop serveHandlers goroutine
	close(pool.hmess)
}
```

connectionHandler.handleMessage() should add select case <-handler.canceled like  connectionHandler.handleError()
```go
func (handler *connectionHandler) handleError(err error, raddr string) {
...
	select {
	case <-handler.canceled:
	case handler.errs <- err:
	}
}
```

**Comment by ghettovoice** [comment]
Hi @liangtu1 ,
you are right. Thanks for report!
