### ISSUE TITLE
got this panic

### ISSUE THREAD

**Issue by czk630597526** [ghettovoice/gosip#69]
panic: send on closed channel

goroutine 15759 [running]:
github.com/ghettovoice/gosip/transport.(*connectionPool).serveHandlers(0xc000434a80)
	D:/goSfu/src/pkg/mod/github.com/ghettovoice/gosip@v0.0.0-20230802091127-d58873a3fe44/transport/connection_pool.go:226 +0xc13
created by github.com/ghettovoice/gosip/transport.NewConnectionPool
	D:/goSfu/src/pkg/mod/github.com/ghettovoice/gosip@v0.0.0-20230802091127-d58873a3fe44/transport/connection_pool.go:101 +0x316

is it caused by #68

**Comment by ghettovoice** [comment]
Hello @czk630597526 ,
not sure it is a direct cause. 
Do you see this error after upgrade? 

Can you also install from this commit `c293573e8f791d79af38f2aaa7db8027113805a5` and try?
```
go get github.com/ghettovoice/gosip@c293573e8f791d79af38f2aaa7db8027113805a5
```
Do you see any errors?

**Comment by czk630597526** [comment]
> Hello @czk630597526 , not sure it is a direct cause. Do you see this error after upgrade?
> 
> Can you also install from this commit `c293573e8f791d79af38f2aaa7db8027113805a5` and try?
> 
> ```
> go get github.com/ghettovoice/gosip@c293573e8f791d79af38f2aaa7db8027113805a5
> ```
> 
> Do you see any errors?

now works well，thank you

**Comment by ghettovoice** [comment]
ok, nice. Thanks for report!
I will make final tests and publish on master.
