### ISSUE TITLE
Why is the transport parameter cleared in the Request-URI?

### ISSUE THREAD

**Issue by kuzmig** [ghettovoice/gosip#70]
Hello!

Could you please clarify why this cleanup of Request-URI tranport parameter was added?
https://github.com/ghettovoice/gosip/blob/c3c83ea9c97665e57a166f6bf8b31c648f7d54a8/transport/layer.go#L290

We just updated to the latest version and it broke some scenarios where we used the transport param to tell the proxy which protocol to use.

Thank you!

**Comment by ghettovoice** [comment]
Hello @kuzmig ,
guess it was a quick patch for other projects based on this lib. 
The patch that obviously shouldn't leak to master here, because `transport` param is allowed in the request URI.

I'm going to remove this lines. Thanks for report👍

**Comment by kuzmig** [comment]
Was fixed by https://github.com/ghettovoice/gosip/commit/afc3f006312fdce32ffc70fe1d91b3435e0af3de
