### ISSUE TITLE
How to remove duplicate UDP packets using UDP mode

### ISSUE THREAD

**Issue by loongyiyao** [ghettovoice/gosip#71]
How to remove duplicate UDP packets using UDP mode？

**Comment by ghettovoice** [comment]
Hello @loongyiyao ,
what kind of duplicates are you talking about?

**Comment by loongyiyao** [comment]
> Hello @loongyiyao , what kind of duplicates are you talking about?

@ghettovoice thanks, For example, due to network reasons, the program receives two identical udp packets, and the business code will receive two requests, leading to business processing exceptions.

**Comment by ghettovoice** [comment]
Who sends these packets? Is it remote sip ua? 
If these requests are identical then they must contains identical Via branch, CSeq and etc regarding to RFC. And such re-transmission requests are absorbed by the server transaction during its live, only the first request is published to upper app layer.
So, if gosip's request handler is triggered multiple times on the similar request, it is actually not identical. Something from transaction ID is differs or transaction already finished. Maybe the remote UA just periodically spams you with similar requests.

**Comment by loongyiyao** [comment]
> Who sends these packets? Is it remote sip ua? If these requests are identical then they must contains identical Via branch, CSeq and etc regarding to RFC. And such re-transmission requests are absorbed by the server transaction during its live, only the first request is published to upper app layer. So, if gosip's request handler is triggered multiple times on the similar request, it is actually not identical. Something from transaction ID is differs or transaction already finished. Maybe the remote UA just periodically spams you with similar requests.

@ghettovoice thanks,I understand what you mean. Currently, Gosip already supports the ability to remove duplicate requests?Can we remove duplicate responses?
For example, the program sends an invite request to the sip server, and the sip server returns only one response. However, due to the intermediate network factors, the response becomes two identical responses. In this case, will the upper transaction office of Gosip receive two response messages?

**Comment by ghettovoice** [comment]
@loongyiyao ok, I see.
Invite transaction state machine (client and server) in gosip is defined as described in RFC 6026. There is additional state "accepted" in which the transaction stays for some time after first 2xx response on INVITE.

Regarding client transaction, the first 2xx response on INVITE and each later 2xx response re-transmissions are passed up to the application. And the application (i.e. UA core) resolves what to do with later response re-transmissions. So the answer on your last question is: yes, you will get every 2xx response.

The INVITE server transaction going to accepted state too, after your first 2xx response. Then each time you retransmit 2xx during this state, it will resend response. Each ACK received during this time will be passed up to application.

Non-invite transactions doesn't have accepted state, so they are destroyed right at the time of in/out 2xx response. This requests can't be forked and there is no reason to absorb re-transmission. For example, the first 2xx response finishes transaction and later re-transmissions will be ignored as responses non-matched to any transaction .

**Comment by loongyiyao** [comment]
> @loongyiyao ok, I see. Invite transaction state machine (client and server) in gosip is defined as described in RFC 6026. There is additional state "accepted" in which the transaction stays for some time after first 2xx response on INVITE.
> 
> Regarding client transaction, the first 2xx response on INVITE and each later 2xx response re-transmissions are passed up to the application. And the application (i.e. UA core) resolves what to do with later response re-transmissions. So the answer on your last question is: yes, you will get every 2xx response.
> 
> The INVITE server transaction going to accepted state too, after your first 2xx response. Then each time you retransmit 2xx during this state, it will resend response. Each ACK received during this time will be passed up to application.
> 
> Non-invite transactions doesn't have accepted state, so they are destroyed right at the time of in/out 2xx response. This requests can't be forked and there is no reason to absorb re-transmission. For example, the first 2xx response finishes transaction and later re-transmissions will be ignored as responses non-matched to any transaction .

@ghettovoice Thanks for your answer. I got it.
