### ISSUE TITLE
Seems there is Memory Leak

### ISSUE THREAD

**Issue by williamyang7577** [ghettovoice/gosip#8]
HI Ghettovoice,
I just create 150 endpoints and  use RequestWithContext do the REGISTER  every 30S,  seems there is memory leak. I saw the usage of this process keep increasing. Below is the capture of the pprof. Please help check. 

Thank You
William

<img width="713" alt="memory-profile" src="https://user-images.githubusercontent.com/57163333/82151831-2a437d00-9890-11ea-9c4c-1e5009a64b04.png">

**Comment by ghettovoice** [comment]
Hello @williamyang7577 ,
thanks for response. I will review this place with profiler. 
Do you can dump here the code that you use? Just as example

**Comment by williamyang7577** [comment]
Hi，
This is my test code ,pls check

**Comment by williamyang7577** [comment]
Hi, 
This is my test code. Please check. 
[test.zip](https://github.com/ghettovoice/gosip/files/4641799/test.zip)
![image](https://user-images.githubusercontent.com/57163333/82170713-d8364200-98f7-11ea-8548-57b7968b75ce.png)


B.R
William
